var postobj = [
    {
      date: '2 September 2017',
      number: 1,
      auth: 'Sudhanshu Agarwal',
      authimg: 'img1auth',
      title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        
      para1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sagittis, sapien a egestas aliquet, erat ipsum tempus lectus, sed sollicitudin elit dui ac odio. Nam sit amet lacus scelerisque, iaculis dolor et, tempor leo. Fusce scelerisque eget augue et consectetur. Cras vitae ante consectetur, luctus neque eget, rutrum ante. Curabitur cursus lorem diam, quis tincidunt nulla luctus sed. Aliquam consequat a erat vel lobortis. Maecenas mattis eget odio in dignissim. Duis nec mauris viverra, tristique nunc molestie, sodales elit.',
      para2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sagittis, sapien a egestas aliquet, erat ipsum tempus lectus, sed sollicitudin elit dui ac odio. Nam sit amet lacus scelerisque, iaculis dolor et, tempor leo. Fusce scelerisque eget augue et consectetur. Cras vitae ante consectetur, luctus neque eget, rutrum ante. Curabitur cursus lorem diam, quis tincidunt nulla luctus sed. Aliquam consequat a erat vel lobortis. Maecenas mattis eget odio in dignissim. Duis nec mauris viverra, tristique nunc molestie, sodales elit.',
      para3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sagittis, sapien a egestas aliquet, erat ipsum tempus lectus, sed sollicitudin elit dui ac odio. Nam sit amet lacus scelerisque, iaculis dolor et, tempor leo. Fusce scelerisque eget augue et consectetur. Cras vitae ante consectetur, luctus neque eget, rutrum ante. Curabitur cursus lorem diam, quis tincidunt nulla luctus sed. Aliquam consequat a erat vel lobortis. Maecenas mattis eget odio in dignissim. Duis nec mauris viverra, tristique nunc molestie, sodales elit.',
      para4: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sagittis, sapien a egestas aliquet, erat ipsum tempus lectus, sed sollicitudin elit dui ac odio. Nam sit amet lacus scelerisque, iaculis dolor et, tempor leo. Fusce scelerisque eget augue et consectetur. Cras vitae ante consectetur, luctus neque eget, rutrum ante. Curabitur cursus lorem diam, quis tincidunt nulla luctus sed. Aliquam consequat a erat vel lobortis. Maecenas mattis eget odio in dignissim. Duis nec mauris viverra, tristique nunc molestie, sodales elit.',
      para5: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sagittis, sapien a egestas aliquet, erat ipsum tempus lectus, sed sollicitudin elit dui ac odio. Nam sit amet lacus scelerisque, iaculis dolor et, tempor leo. Fusce scelerisque eget augue et consectetur. Cras vitae ante consectetur, luctus neque eget, rutrum ante. Curabitur cursus lorem diam, quis tincidunt nulla luctus sed. Aliquam consequat a erat vel lobortis. Maecenas mattis eget odio in dignissim. Duis nec mauris viverra, tristique nunc molestie, sodales elit.',
      para6: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sagittis, sapien a egestas aliquet, erat ipsum tempus lectus, sed sollicitudin elit dui ac odio. Nam sit amet lacus scelerisque, iaculis dolor et, tempor leo. Fusce scelerisque eget augue et consectetur. Cras vitae ante consectetur, luctus neque eget, rutrum ante. Curabitur cursus lorem diam, quis tincidunt nulla luctus sed. Aliquam consequat a erat vel lobortis. Maecenas mattis eget odio in dignissim. Duis nec mauris viverra, tristique nunc molestie, sodales elit.',
      para7: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sagittis, sapien a egestas aliquet, erat ipsum tempus lectus, sed sollicitudin elit dui ac odio. Nam sit amet lacus scelerisque, iaculis dolor et, tempor leo. Fusce scelerisque eget augue et consectetur. Cras vitae ante consectetur, luctus neque eget, rutrum ante. Curabitur cursus lorem diam, quis tincidunt nulla luctus sed. Aliquam consequat a erat vel lobortis. Maecenas mattis eget odio in dignissim. Duis nec mauris viverra, tristique nunc molestie, sodales elit.',
        
      coverphoto: 'img1cover',
      coverphototxt: 'Tamalpais-Homestead Valley, CA &copy; Sudhanshu Agarwal',
      photo1: 'noshow',
      photo1txt: '',
      photo2: 'noshow',
      photo2txt: '',
      photo3: 'noshow',
      photo3txt: '',
      code1: 'noshow',
      code2: 'noshow',
      code3: 'noshow',
      code4: 'noshow',
      code5: 'noshow',
      code6: 'noshow',
      code7: 'noshow',
      code8: 'noshow'
    },
    {
      date: '2 September 2017',
      number: 2,
      auth: 'Sudhanshu Agarwal',
      authimg: 'img2auth',
      title: 'Hello World!',
      para1: 'Hello World! I am starting a blog designed using Materialize CSS and hosted on GitHub pages. I will usually post random or science stuff. I will usually update it every fornight. I will start it by writing about my Google Code-in 2016 experience.',
      para2: 'I am a big fan of simplicity and material design and you can see this in this website."',
      para3: 'Starting with a little about me, I am Sudhanshu Agarwal and Hi, it is great to meet you! I am a quizzer and a programmer and also I am deep into music.',
      para4: 'I was a Grand Prize Winner with BRL-CAD in Google Code-in 2016 but watch out for my next post for more details.',
      para5: 'I hope that you will enjoy reading the rest of the posts and please feel free to contact me via the contact me page whose link is floating in the bottom left of the website.',
      para6: 'Thanks for reading this!',
      para7: 'P.S. If you liked the post, please click on the heart in bottom right corner.',
      coverphoto: 'img2cover',
      coverphototxt: 'San Francisco&#45;Oakland Bay Bridge, CA &copy; Sudhanshu Agarwal',
      photo1: 'noshow',
      photo1txt: '',
      photo2: 'noshow',
      photo2txt: '',
      photo3: 'noshow',
      photo3txt: '',
      code1: 'cout&lt;&lt;&quot;Hello World&quot;&#59;',
      code2: 'noshow',
      code3: 'noshow',
      code4: 'noshow',
      code5: 'noshow',
      code6: 'noshow',
      code7: 'noshow',
      code8: 'noshow'
    }
  ]